# Generated by Django 5.0 on 2024-05-24 00:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('descripcion', models.TextField(max_length=200)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=100)),
                ('ubicacion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Vuelos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.TextField(max_length=100)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('origen_vuelo', models.CharField(max_length=100)),
                ('destino_vuelo', models.CharField(max_length=100)),
                ('hora_salida', models.TimeField()),
                ('duracion_horas', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Reserva_hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('fecha_reserva', models.DateTimeField(auto_now_add=True)),
                ('check_in', models.DateTimeField(auto_now=True)),
                ('check_out', models.DateTimeField(auto_now=True)),
                ('duracion_reserva', models.DurationField()),
                ('tarifa_noche', models.DecimalField(decimal_places=2, max_digits=10)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viajefacil.hotel')),
            ],
        ),
        migrations.CreateModel(
            name='Reserva_vuelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('fecha_reserva', models.DateTimeField(auto_now_add=True)),
                ('check_in', models.DateTimeField(auto_now=True)),
                ('check_out', models.DateTimeField(auto_now=True)),
                ('duracion_reserva', models.DurationField()),
                ('vuelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viajefacil.vuelos')),
            ],
        ),
    ]
