# Generated by Django 5.0 on 2024-05-24 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viajefacil', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='destino',
            options={'verbose_name_plural': 'Destino'},
        ),
        migrations.AlterModelOptions(
            name='hotel',
            options={'verbose_name_plural': 'Hotel'},
        ),
        migrations.AlterModelOptions(
            name='reserva_hotel',
            options={'verbose_name_plural': 'Reserva_hotel'},
        ),
        migrations.AlterModelOptions(
            name='reserva_vuelo',
            options={'verbose_name_plural': 'Reserva_vuelo'},
        ),
        migrations.AlterModelOptions(
            name='vuelos',
            options={'verbose_name_plural': 'Vuelos'},
        ),
    ]
