# Generated by Django 5.0 on 2024-05-24 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viajefacil', '0002_alter_destino_options_alter_hotel_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva_hotel',
            name='check_in',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='reserva_hotel',
            name='check_out',
            field=models.DateTimeField(),
        ),
    ]
