# Generated by Django 5.0 on 2024-05-24 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viajefacil', '0003_alter_reserva_hotel_check_in_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva_hotel',
            name='tarifa_noche',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
    ]
