# Generated by Django 5.0 on 2024-05-24 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viajefacil', '0005_alter_reserva_hotel_duracion_reserva'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva_hotel',
            name='fecha_reserva',
            field=models.DateTimeField(),
        ),
    ]
