# Generated by Django 5.0 on 2024-05-24 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viajefacil', '0006_alter_reserva_hotel_fecha_reserva'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva_hotel',
            name='fecha_reserva',
        ),
    ]
