# Generated by Django 5.0 on 2024-05-24 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viajefacil', '0007_remove_reserva_hotel_fecha_reserva'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva_hotel',
            name='fin_reserva',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='reserva_hotel',
            name='inicio_reserva',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
