# Generated by Django 5.0 on 2024-05-24 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viajefacil', '0009_alter_reserva_hotel_duracion_reserva'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva_hotel',
            name='fin_reserva',
        ),
        migrations.RemoveField(
            model_name='reserva_hotel',
            name='inicio_reserva',
        ),
    ]
