# Generated by Django 5.0 on 2024-05-25 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viajefacil', '0012_reserva_hotel_fin_reserva_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva_hotel',
            name='inicio_reserva',
            field=models.DateTimeField(),
        ),
    ]
