# Generated by Django 5.0 on 2024-05-25 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viajefacil', '0013_alter_reserva_hotel_inicio_reserva'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva_hotel',
            name='fin_reserva',
            field=models.DateTimeField(),
        ),
    ]
