# Generated by Django 5.0 on 2024-06-19 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viajefacil', '0016_paquetes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destino',
            name='precio',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
        migrations.DeleteModel(
            name='Reserva_vuelo',
        ),
        migrations.DeleteModel(
            name='Vuelos',
        ),
    ]
