# Generated by Django 5.0 on 2024-06-19 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viajefacil', '0017_alter_destino_precio_delete_reserva_vuelo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='habitacion',
            field=models.CharField(default='habitacion', max_length=10),
            preserve_default=False,
        ),
    ]
