# Generated by Django 5.0 on 2024-06-21 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viajefacil', '0018_hotel_habitacion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotel',
            old_name='titulo',
            new_name='nombre',
        ),
    ]
