# Generated by Django 5.0 on 2024-06-21 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viajefacil', '0019_rename_titulo_hotel_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='precio',
            field=models.DecimalField(decimal_places=0, default='0', max_digits=10),
            preserve_default=False,
        ),
    ]
