# Generated by Django 5.0 on 2024-06-21 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viajefacil', '0020_hotel_precio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='precio',
        ),
    ]
