# Generated by Django 5.0 on 2024-06-21 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viajefacil', '0023_hotel_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva_hotel',
            name='tarifa_noche',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
