# Generated by Django 5.0 on 2024-06-21 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viajefacil', '0026_alter_hotel_precio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='precio',
        ),
    ]
