# Generated by Django 5.0 on 2024-06-21 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viajefacil', '0028_hotel_precio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='precio',
        ),
        migrations.AlterField(
            model_name='hotel',
            name='descripcion',
            field=models.CharField(max_length=100),
        ),
    ]
