# Generated by Django 5.0 on 2024-06-21 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viajefacil', '0029_remove_hotel_precio_alter_hotel_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='precio',
            field=models.CharField(default='valor', max_length=100),
            preserve_default=False,
        ),
    ]
