# Generated by Django 5.0 on 2024-06-21 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viajefacil', '0030_hotel_precio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotel',
            old_name='precio',
            new_name='tarifa',
        ),
    ]
