# Generated by Django 5.0 on 2024-06-21 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viajefacil', '0031_rename_precio_hotel_tarifa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='tarifa',
        ),
    ]
