# Generated by Django 5.0 on 2024-06-21 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viajefacil', '0032_remove_hotel_tarifa'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='ubicacion1',
            field=models.CharField(default='ubi', max_length=100),
            preserve_default=False,
        ),
    ]
