# Generated by Django 5.0 on 2024-06-21 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viajefacil', '0033_hotel_ubicacion1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='ubicacion1',
        ),
        migrations.AddField(
            model_name='hotel',
            name='precio',
            field=models.DecimalField(decimal_places=0, default=100.0, max_digits=10),
            preserve_default=False,
        ),
    ]
