# Generated by Django 5.0 on 2024-06-21 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viajefacil', '0034_remove_hotel_ubicacion1_hotel_precio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotel',
            old_name='precio',
            new_name='tarifa_noche',
        ),
    ]
