# Generated by Django 5.0 on 2024-06-21 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viajefacil', '0036_alter_destino_precio_alter_hotel_tarifa_noche_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='tarifa_noche',
        ),
    ]
