# Generated by Django 5.0 on 2024-06-21 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viajefacil', '0037_remove_hotel_tarifa_noche'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
