# Generated by Django 5.0 on 2024-06-21 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viajefacil', '0042_remove_hotel_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='estrellas',
            field=models.CharField(default='valor', max_length=110),
            preserve_default=False,
        ),
    ]
