# Generated by Django 5.0 on 2024-06-22 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viajefacil', '0043_hotel_estrellas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='estrellas',
        ),
    ]
