# Generated by Django 5.0 on 2024-06-22 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viajefacil', '0044_remove_hotel_estrellas'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
