# Generated by Django 5.0 on 2024-06-24 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viajefacil', '0049_alter_reserva_hotel_tarifa_noche'),
    ]

    operations = [
        migrations.AddField(
            model_name='destino',
            name='ubicacion',
            field=models.TextField(default='ubicacion', max_length=100),
            preserve_default=False,
        ),
    ]
