# Generated by Django 5.0 on 2024-06-25 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viajefacil', '0051_remove_destino_ubicacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='destino',
            name='ubicacion',
            field=models.TextField(default='ubicacion', max_length=200),
            preserve_default=False,
        ),
    ]
