# Generated by Django 5.0 on 2024-06-25 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viajefacil', '0052_destino_ubicacion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Paquetes',
        ),
    ]
