# Generated by Django 5.0 on 2024-07-03 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viajefacil', '0055_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
