# Generated by Django 5.0 on 2024-07-03 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viajefacil', '0058_alter_paquete_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paquete',
            name='mascota',
            field=models.CharField(max_length=100),
        ),
    ]
